### PR TITLE
Revert "GPG-164 Admin page to re-add retired submissions (will only b…

### PR DESCRIPTION
**Pull request by AlexJacksonDS**
…e used once, then removed)"

This reverts commit 60635aa40c07540c2990a3232054fe02b8e8a420.

### CODE REVIEW

**Comment by Binney** [comment]
Can I ask you to add a quick comment around any testing you've done here? Also, as we don't tend to squash commits, is this the only commit we need to revert?

**Comment by AlexJacksonDS** [comment]
Yeah this is the only commit that needs reverting to remove the functionality, it was all added in a single commit.

For testing, I just confirmed that the endpoint is no longer accessible, and a bit of clicking around the rest of the site. It wasn't linked anywhere so we have no broken links.

**Review by Binney — APPROVED** [review]
Awesome stuff, thanks

**Review by dulciejackson — APPROVED** [review]
Good stuff! :)

**Pull request merged**
