### PR TITLE
GPG-866: Configured terraform setup

### PR DESCRIPTION
**Pull request by LadunOmideyiSoftwire**
This creates the most barebones version of a multiple s3 remote back up I could, without resorting to new project directories.

- - -
This change is [Reviewable](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458)

### CODE REVIEW

**Review by benbelow — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458)* status: all files reviewed, 7 unresolved discussions (waiting on @LadunOmideyiSoftwire)

___
*[`terraform/dev-backend.conf` line 1 at r1](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N96194g4l-gjIo11xa6:-N96194g4l-gjIo11xa7:b31ufpf) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/0ee97dc9ef3ba0892c0fe70543e8d82bbf5a8b87/terraform/dev-backend.conf#L1)):*
> ```
> 
> ```

this is slightly different to how I've used terraform state before (in azure) - previously I've used workspaces to differentiate between environments. 

i.e. we'd have a single bucket/dynamo-db in a shared AWS account, independent of the three environments we'll spin up.

Each workspace in terraform will create state data in a new file in this shared bucket, suffixed with the workspace name (for which we would use environment names).


Did you actively decide that we need a separate bucket for each environment? If not, I would lean towards switching to workspaces, as it allows our environments to be decoupled from our codebase - i.e. we don't need to make code changes to spin up a new environment 
___
*[`terraform/provider.tf` line 23 at r1](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N9634hh4nXDbhv6q0lU:-N9634hh4nXDbhv6q0lV:b-yalwf6) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/0ee97dc9ef3ba0892c0fe70543e8d82bbf5a8b87/terraform/provider.tf#L23)):*
> ```HCL
> 
> locals {
>   infra_env = terraform.workspace == "default"  ? "dev" : terraform.workspace
> ```

I feel like we should split out "dev" into a default workspace local (So we can re-use it in the terraform scripts without duplication), if not a variable (so we can change the default workspace name without a code change)
___
*[`terraform/provider.tf` line 27 at r1](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N963Fu74b2rp-PtxdQ9:-N963Fu74b2rp-PtxdQA:b-p1ocnl) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/0ee97dc9ef3ba0892c0fe70543e8d82bbf5a8b87/terraform/provider.tf#L27)):*
> ```HCL
> 
> provider "aws" {
>   # Configuration options
> ```

I don't feel like this comment is telling us anything useful
___
*[`terraform/variables.tf` line 3 at r1](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N963RTo0VlNUgJ4Rg21:-N963RTo0VlNUgJ4Rg22:b510j9b) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/0ee97dc9ef3ba0892c0fe70543e8d82bbf5a8b87/terraform/variables.tf#L3)):*
> ```HCL
> // all declared input variables
> 
> variable "bucket_prefix" {
> ```

I may have missed something here, what is this used for?
___
*[`terraform/variables.tf` line 11 at r1](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N963UjB6PKN9yRx_Uys:-N963UjB6PKN9yRx_Uyt:b213wc2) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/0ee97dc9ef3ba0892c0fe70543e8d82bbf5a8b87/terraform/variables.tf#L11)):*
> ```HCL
> variable "acl" {
>   type        = string
>   description = "(Optional) Defaults to private. Conflicts with grant."
> ```

can we spell out what acl stands for? 
___
*[`terraform/variables.tf` line 11 at r1](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N963YEb6i1YlAI0mNGX:-N963YEb6i1YlAI0mNGY:bonj853) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/0ee97dc9ef3ba0892c0fe70543e8d82bbf5a8b87/terraform/variables.tf#L11)):*
> ```HCL
> variable "acl" {
>   type        = string
>   description = "(Optional) Defaults to private. Conflicts with grant."
> ```

what does "Conflicts with grant" mean? 
___
*[`terraform/variables.tf` line 17 at r1](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N963eOe-HMTjedtHhxv:-N963eOe-HMTjedtHhxw:b92mze8) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/0ee97dc9ef3ba0892c0fe70543e8d82bbf5a8b87/terraform/variables.tf#L17)):*
> ```HCL
> variable "versioning" {
>   type        = bool
>   description = "(Optional) A state of versioning."
> ```

this documentation doesn't really tell me what's going on here. Additionally, I can't find any usages of this variable - what will it be used for?

**Review by benbelow — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458)* status: all files reviewed, 3 unresolved discussions (waiting on @LadunOmideyiSoftwire)

___
*[`terraform/main.tf` line 5 at r2](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N9GmJjuB1lEx0MFfx8Z:-N9GmJjuB1lEx0MFfx8_:b-ibr7zn) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/c22fc5c233ecadb12ae4c1dfde518258b80cb5f8/terraform/main.tf#L5)):*
> ```HCL
> 
> 
> module "s3_bucket" {
> ```

(even though it's an example resource, let's aim to use good practices anyway)

we should give this a useful name so we can reference it elsewhere in the terraform scripts
___
*[`terraform/provider.tf` line 23 at r2](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N9Gm3_B0s6owiW06SkE:-N9Gm3_B0s6owiW06SkF:b-j45k2) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/c22fc5c233ecadb12ae4c1dfde518258b80cb5f8/terraform/provider.tf#L23)):*
> ```HCL
>     region = "eu-west-2"
>     encrypt = true
>     workspace_key_prefix = "gpg-"
> ```

now that we know this essentially works as a folder, we should maybe remove the dash here to look a bit nicer in aws

**Review by LadunOmideyiSoftwire — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458)* status: all files reviewed, 2 unresolved discussions (waiting on @LadunOmideyiSoftwire)

___
*[`terraform/dev-backend.conf` line 1 at r1](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N96194g4l-gjIo11xa6:-N9GVP5f7N-n_DwcJGwh:b-896fix) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/0ee97dc9ef3ba0892c0fe70543e8d82bbf5a8b87/terraform/dev-backend.conf#L1)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

this is slightly different to how I've used terraform state before (in azure) - previously I've used workspaces to differentiate between environments. 

i.e. we'd have a single bucket/dynamo-db in a shared AWS account, independent of the three environments we'll spin up.

Each workspace in terraform will create state data in a new file in this shared bucket, suffixed with the workspace name (for which we would use environment names).


Did you actively decide that we need a separate bucket for each environment? If not, I would lean towards switching to workspaces, as it allows our environments to be decoupled from our codebase - i.e. we don't need to make code changes to spin up a new environment 
</blockquote></details>

Done.
___
*[`terraform/provider.tf` line 23 at r1](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N9634hh4nXDbhv6q0lU:-N9GXn2v8iDoK1yoOVdM:b-896fix) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/0ee97dc9ef3ba0892c0fe70543e8d82bbf5a8b87/terraform/provider.tf#L23)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

I feel like we should split out "dev" into a default workspace local (So we can re-use it in the terraform scripts without duplication), if not a variable (so we can change the default workspace name without a code change)
</blockquote></details>

Done.
___
*[`terraform/provider.tf` line 27 at r1](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N963Fu74b2rp-PtxdQ9:-N9GWvoX9QldBRmWwe82:b-896fix) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/0ee97dc9ef3ba0892c0fe70543e8d82bbf5a8b87/terraform/provider.tf#L27)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

I don't feel like this comment is telling us anything useful
</blockquote></details>

Done.
___
*[`terraform/variables.tf` line 3 at r1](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N963RTo0VlNUgJ4Rg21:-N9GZ_CR1J6apc0vNvVZ:b-896fix) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/0ee97dc9ef3ba0892c0fe70543e8d82bbf5a8b87/terraform/variables.tf#L3)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

I may have missed something here, what is this used for?
</blockquote></details>

Done.
___
*[`terraform/variables.tf` line 11 at r1](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N963YEb6i1YlAI0mNGX:-N9GZaTF7tAOeMyzqD5G:b-896fix) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/0ee97dc9ef3ba0892c0fe70543e8d82bbf5a8b87/terraform/variables.tf#L11)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

what does "Conflicts with grant" mean? 
</blockquote></details>

Done.
___
*[`terraform/variables.tf` line 11 at r1](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N963UjB6PKN9yRx_Uys:-N9GZbAG1ll8-unzaa5m:b-896fix) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/0ee97dc9ef3ba0892c0fe70543e8d82bbf5a8b87/terraform/variables.tf#L11)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

can we spell out what acl stands for? 
</blockquote></details>

Done.
___
*[`terraform/variables.tf` line 17 at r1](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N963eOe-HMTjedtHhxv:-N9GfDid9aX3GcPDXyBo:b-896fix) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/0ee97dc9ef3ba0892c0fe70543e8d82bbf5a8b87/terraform/variables.tf#L17)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

this documentation doesn't really tell me what's going on here. Additionally, I can't find any usages of this variable - what will it be used for?
</blockquote></details>

Done.

**Review by LadunOmideyiSoftwire — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458)* status: all files reviewed, 2 unresolved discussions (waiting on @benbelow)

___
*[`terraform/main.tf` line 5 at r2](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N9GmJjuB1lEx0MFfx8Z:-N9GoIEIEHYFAiK6lqO9:b-896fix) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/c22fc5c233ecadb12ae4c1dfde518258b80cb5f8/terraform/main.tf#L5)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

(even though it's an example resource, let's aim to use good practices anyway)

we should give this a useful name so we can reference it elsewhere in the terraform scripts
</blockquote></details>

Done.
___
*[`terraform/provider.tf` line 23 at r2](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458#-N9Gm3_B0s6owiW06SkE:-N9GoYFw9H92gC0oGLmz:b-896fix) ([raw file](https://github.com/cabinetoffice/gender-pay-gap/blob/c22fc5c233ecadb12ae4c1dfde518258b80cb5f8/terraform/provider.tf#L23)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

now that we know this essentially works as a folder, we should maybe remove the dash here to look a bit nicer in aws
</blockquote></details>

Done.

**Review by benbelow — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @LadunOmideyiSoftwire)

**Pull request merged**
